### ISSUE TITLE
NullPointerException running build

### ISSUE THREAD

**Issue by geoffbullen** [boxuk/jslint-jenkins-plugin#1]
Hey,

Getting the following exception when running this plugin.  Am I missing any config??

``` javascript
[JSLint] Ready
[JSLint] calling jslint with args[-DxmlOutput=C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace/jslint.xml, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\css\PIE.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\css\PIE_uncompressed.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\build-pipeline.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\handlebars-1.0.0.beta.6.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\jquery-1.7.1.min.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\jquery-ui-1.8.14.custom.min.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\jquery.1.5.1.min.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\jquery.fancybox-1.3.4.js, C:\workspace\yflowing\target\package\flow\jenkins\jobs\Build Pipeline Plugin Compile\workspace\src\main\webapp\js\jquery.tooltip.min.js]
FATAL: null
java.lang.NullPointerException
    at com.boxuk.jenkins.jslint.LintRunner.call(LintRunner.java:98)
    at com.boxuk.jenkins.jslint.LintRunner.call(LintRunner.java:25)
    at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
    at com.boxuk.jenkins.jslint.JSLintBuilder.perform(JSLintBuilder.java:102)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractRunner.perform(AbstractBuild.java:710)
    at hudson.model.Build$RunnerImpl.build(Build.java:178)
    at hudson.model.Build$RunnerImpl.doRun(Build.java:139)
    at hudson.model.AbstractBuild$AbstractRunner.run(AbstractBuild.java:480)
    at hudson.model.Run.run(Run.java:1434)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:239)
'''
```

**Comment by gavD** [comment]
Hi Geoff, looks like this is an issue in a pure Windows implementation where it can't find jslint.js - can you confirm you're using a Windows master Jenkins server?

If that's the case, I will set up a Windows Jenkins master and investigate further

**Comment by Hagendorn** [comment]
Hi,

I have the same problem, but I use a UNIX system.

Cheers,
Chris

**Comment by gavD** [comment]
OK, this means that the plugin is unable to find the JSLint/jslint.js resource. Please could you tell me:
1. What version of Jenkins are you using?
2. If you look in $JENKINS_HOME/plugins/ and then do something like "find . -name "jslint.js", does anything come up?

I'm wondering if perhaps the installer didn't place the resource correctly

Thanks for your help on this guys, I really appreciate the feedback!

**Comment by gavD** [comment]
Also:
1. Are you using a Master/Slaves configuration of Jenkins, or a single server?
2. What version of the JSLint plugin are you using, and how did you build it?

Thanks,
- Gav

**Comment by Hagendorn** [comment]
Hi Gav,

thanks for the fast answer!
1. Jenkins ver. 1.477
2. find . -name "jslint.js"
   ./jslint/WEB-INF/classes/com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js
3. We use Jenkins as single server
4. This morning I checked out the repository with HEAD 4c0155d5 an build it with maven (shell call "mvn")

Cheers,
Chris

**Comment by Hagendorn** [comment]
Jenkins shows me the version number 0.6.7 for the JSLint plugin.

**Comment by gavD** [comment]
Thanks Chris, that's really helpful, I think we're getting somewhere! :-)

On my machine, I get:

```
gavd@gavd-desktop:/var/lib/jenkins/plugins# find . -name "jslint.js"
./jslint/WEB-INF/classes/com/boxuk/jenkins/jslint/JSLint/jslint.js
./jslint/WEB-INF/classes/com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js
```

So could you please try:

```
cp ./jslint/WEB-INF/classes/com/boxuk/jenkins/jslint/JSLintBuilder/jslint.js ./jslint/WEB-INF/classes/com/boxuk/jenkins/jslint/JSLint/jslint.js 
```

If this resolves the problem, then I will patch it in the Git repo today

Thanks again for your help!

**Comment by Hagendorn** [comment]
I copied the file successfully and the NullPointExecption is gone, but now I got a FileNotFoundException 

FATAL: Wrapped java.io.FileNotFoundException: /var/lib/jenkins/jobs/appMessaging/workspace (Is a directory) (jslint.js#5690)
org.mozilla.javascript.WrappedException: Wrapped java.io.FileNotFoundException: /var/lib/jenkins/jobs/appMessaging/workspace (Is a directory) (jslint.js#5690)
    at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1773)
    at org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:202)
    at org.mozilla.javascript.NativeJavaClass.constructSpecific(NativeJavaClass.java:281)
    at org.mozilla.javascript.NativeJavaClass.construct(NativeJavaClass.java:200)
    at org.mozilla.javascript.ScriptRuntime.newObject(ScriptRuntime.java:2327)
    at org.mozilla.javascript.gen.c2._c149(jslint.js:5690)
    at org.mozilla.javascript.gen.c2.call(jslint.js)
    at org.mozilla.javascript.optimizer.OptRuntime.call1(OptRuntime.java:66)
    at org.mozilla.javascript.gen.c2._c0(jslint.js:5591)
    at org.mozilla.javascript.gen.c2.call(jslint.js)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
    at org.mozilla.javascript.gen.c2.call(jslint.js)
    at org.mozilla.javascript.gen.c2.exec(jslint.js)
    at org.mozilla.javascript.Context.evaluateReader(Context.java:1135)
    at com.boxuk.jenkins.jslint.LintRunner.call(LintRunner.java:101)
    at com.boxuk.jenkins.jslint.LintRunner.call(LintRunner.java:25)
    at hudson.remoting.LocalChannel.call(LocalChannel.java:45)
    at com.boxuk.jenkins.jslint.JSLintBuilder.perform(JSLintBuilder.java:102)
    at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:19)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:717)
    at hudson.model.Build$BuildExecution.build(Build.java:199)
    at hudson.model.Build$BuildExecution.doRun(Build.java:160)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:499)
    at hudson.model.Run.execute(Run.java:1502)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:46)
    at hudson.model.ResourceController.execute(ResourceController.java:88)
    at hudson.model.Executor.run(Executor.java:236)
Caused by: java.io.FileNotFoundException: /var/lib/jenkins/jobs/appMessaging/workspace (Is a directory)
    at java.io.FileOutputStream.open(Native Method)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:194)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:84)
    at java.io.FileWriter.<init>(FileWriter.java:46)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:39)
    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:27)
    at java.lang.reflect.Constructor.newInstance(Constructor.java:513)
    at org.mozilla.javascript.MemberBox.newInstance(MemberBox.java:194)
    ... 26 more

**Comment by gavD** [comment]
I wasn't able to reproduce this error, but it looks like it didn't match any files or somehow matched just the workspace directory - what configuration do you have on the plugin in your job?

I have, in one of my test projects, the following configuration set on the jslint plugin:
Files to scan: *_/_.js
Files to exclude: 
Log file: jslint.xml

Thanks,
- Gav

**Comment by Hagendorn** [comment]
Ok, sorry my fault. I removed the value for the "Log file", due to some tests. Now it works. Thanks!

**Comment by gavD** [comment]
Great, thanks Chris!

Looks like I have a couple of things to do for version 0.7:
1. Add validation of the log file
2. Make sure the jslint.js file is found

Many thanks for your help!

**Comment by gavD** [comment]
From version 0.7.0 onwards, this should work for you. Please re-open this ticket if problems persist

Thanks,
- Gav
